/* ═══════════════════════════════════════════════════════════
   cyrus.ai — developer programs + organizations datasets
   Months are floats on a Jan=0 .. Dec=11 scale (2026 snapshot).
   "now" = 9.x (October). Stars/repos are curated estimates.
   ═══════════════════════════════════════════════════════════ */

const PROGRAMS = [
  {
    id: "gsoc", name: "Google Summer of Code", owner: "google",
    img: "assets/prog-gsoc.jpg", url: "https://summerofcode.withgoogle.com",
    tag: "Write real code for open-source orgs, mentored full-time over the summer.",
    pay: "$1,500 – $3,300", payNote: "STIPEND",
    status: "closed", window: "Applications close April",
    orgs: "900+ orgs", slots: "~3,800 students",
    phases: [
      { label: "Org applications", s: 0, e: 1.6, c: "#3b6ea5" },
      { label: "Student applications", s: 2.1, e: 3.8, c: "#b4602c" },
      { label: "Community bonding", s: 3.8, e: 4.6, c: "#7a5aa8" },
      { label: "Coding period", s: 4.6, e: 8.2, c: "#3e7d4f" },
    ],
  },
  {
    id: "outreachy", name: "Outreachy", owner: "outreachy",
    img: "assets/prog-outreachy.jpg", url: "https://www.outreachy.org",
    tag: "Paid remote internships in open source for people from under-represented groups.",
    pay: "$8,000 USD", payNote: "PER INTERNSHIP",
    status: "upcoming", window: "Dec cohort pairing opens Nov",
    orgs: "150+ communities", slots: "~120 interns",
    phases: [
      { label: "Outreach period", s: 10.2, e: 11.2, c: "#3b6ea5" },
      { label: "Applications", s: 1.6, e: 3.1, c: "#b4602c" },
      { label: "Internship (May cohort)", s: 4, e: 8, c: "#3e7d4f" },
      { label: "Internship (Dec cohort)", s: 11, e: 12, c: "#7a5aa8" },
    ],
  },
  {
    id: "lfx", name: "LFX Mentorship", owner: "linuxfoundation",
    img: "assets/prog-lfx.jpg", url: "https://mentorship.lfx.linuxfoundation.org",
    tag: "Cloud & ecosystem mentored projects across Linux Foundation host projects.",
    pay: "$1,500 – $3,000", payNote: "PER TERM",
    status: "live", window: "Term 3 running now · Sep – Nov",
    orgs: "100+ projects", slots: "300+ mentees",
    phases: [
      { label: "Term 1", s: 2, e: 5, c: "#3b6ea5" },
      { label: "Term 2", s: 5, e: 8, c: "#7a5aa8" },
      { label: "Term 3", s: 8.3, e: 11, c: "#3e7d4f", active: true },
    ],
  },
  {
    id: "esoc", name: "Eclipse SoC", owner: "eclipse-foundation",
    img: "assets/prog-esoc.jpg", url: "https://soc.eclipse.to",
    tag: "Summer contributions to Eclipse Foundation projects with structured mentoring.",
    pay: "€500 – €1,200", payNote: "PER PROJECT",
    status: "closed", window: "Runs May – August",
    orgs: "40+ projects", slots: "~60 contributors",
    phases: [
      { label: "Project proposals", s: 2.8, e: 4.2, c: "#3b6ea5" },
      { label: "Teams formed", s: 4.2, e: 4.9, c: "#a97b1f" },
      { label: "Coding & demos", s: 4.9, e: 7.6, c: "#3e7d4f" },
    ],
  },
  {
    id: "mlh", name: "MLH Fellowship", owner: "MLH",
    img: "assets/prog-alt-roorkee.jpg", url: "https://fellowship.mlh.io",
    tag: "A remote, batch-based alternative to internships on real open-source teams.",
    pay: "Paid tracks", payNote: "UP TO $2K/MO",
    status: "live", window: "Fall batch in session",
    orgs: "30+ partner orgs", slots: "Small cohorts",
    phases: [
      { label: "Spring batch", s: 2.5, e: 5, c: "#3b6ea5" },
      { label: "Summer batch", s: 5.3, e: 7.8, c: "#7a5aa8" },
      { label: "Fall batch", s: 8.2, e: 10.8, c: "#3e7d4f", active: true },
    ],
  },
  {
    id: "gssoc", name: "GSSoC'26", owner: "GirlScript",
    img: "assets/prog-gsoc.jpg", url: "https://gssoc.girlscript.tech",
    tag: "Three-month open-source contribution sprint, biggest women-led program in India.",
    pay: "Leaderboard prizes", payNote: "SWAG + CERTS",
    status: "live", window: "Contributions Aug – Nov",
    orgs: "200+ projects", slots: "Open to all",
    phases: [
      { label: "Registration", s: 6.3, e: 7.4, c: "#3b6ea5" },
      { label: "Contribution period", s: 7.4, e: 10.6, c: "#b4602c", active: true },
      { label: "Evaluation", s: 10.6, e: 11.2, c: "#a97b1f" },
    ],
  },
  {
    id: "kde", name: "Season of KDE", owner: "kde",
    img: "assets/prog-lfx.jpg", url: "https://season.kde.org",
    tag: "Winter mentoring program for KDE — design, code, docs, and community work.",
    pay: "€300 – €1,000", payNote: "PRIZES",
    status: "upcoming", window: "Registrations open December",
    orgs: "KDE ecosystem", slots: "Global",
    phases: [
      { label: "Ideas list", s: 9.4, e: 10.6, c: "#3b6ea5" },
      { label: "Registration", s: 11, e: 12, c: "#b4602c" },
      { label: "Mentoring", s: 0, e: 2.9, c: "#3e7d4f" },
    ],
  },
  {
    id: "oct", name: "Hacktoberfest", owner: "github",
    img: "assets/prog-outreachy.jpg", url: "https://hacktoberfest.com",
    tag: "One month of pull requests, first-timer friendly, the on-ramp for most contributors.",
    pay: "Badge + tree", payNote: "PER PARTICIPANT",
    status: "live", window: "All of October · you are here",
    orgs: "All of GitHub", slots: "Millions",
    phases: [
      { label: "Prep & first-timer issues", s: 8.3, e: 9, c: "#7a5aa8" },
      { label: "Hacktoberfest", s: 9, e: 10, c: "#3e7d4f", active: true },
    ],
  },
];

/* Popular GitHub organizations — login doubles as the official-logo source:
   https://github.com/{login}.png */
const ORGS = [
  { login: "google", name: "Google", domain: "developers.google.com", level: "advanced",
    tagline: "TensorFlow, Go, Angular, GEMINI — the largest OSS footprint on GitHub.", tags: ["AI/ML", "Cloud", "Languages"], repos: 3200, stars: 762000, issues: 21400 },
  { login: "microsoft", name: "Microsoft", domain: "microsoft.github.io", level: "intermediate",
    tagline: "VS Code, TypeScript, .NET, PowerToys — ships more stars than anyone.", tags: ["Dev tools", "Languages", ".NET"], repos: 5400, stars: 904000, issues: 30800 },
  { login: "anthropics", name: "Anthropic", domain: "anthropic.com", level: "beginner",
    tagline: "Claude SDKs and the agent-skills playbook every coding agent builds on.", tags: ["AI agents", "Skills", "SDKs"], repos: 84, stars: 322000, issues: 940 },
  { login: "openai", name: "OpenAI", domain: "openai.com", level: "intermediate",
    tagline: "GPT ecosystem: Whisper, Codex CLI, evals, cookbook — fast-moving APIs.", tags: ["AI", "LLM tools", "Python"], repos: 210, stars: 289000, issues: 1600 },
  { login: "huggingface", name: "Hugging Face", domain: "huggingface.co", level: "beginner",
    tagline: "Transformers, Hub, datasets, gradio — the home of open model sharing.", tags: ["ML", "Datasets", "Community"], repos: 590, stars: 268000, issues: 5200 },
  { login: "modelcontextprotocol", name: "Model Context Protocol", domain: "modelcontextprotocol.io", level: "beginner",
    tagline: "The USB-C of AI: one spec, thousands of MCP servers for agent tool use.", tags: ["MCP", "Standards", "Agents"], repos: 60, stars: 76000, issues: 800 },
  { login: "vercel", name: "Vercel", domain: "vercel.com", level: "beginner",
    tagline: "Next.js, Turbopack, AI SDK — front-edge tooling used by half the web.", tags: ["Frontend", "AI SDK", "DX"], repos: 420, stars: 198000, issues: 6900 },
  { login: "cloudflare", name: "Cloudflare", domain: "developers.cloudflare.com", level: "intermediate",
    tagline: "Workers, Wrangler, Turnstile — edge compute with sane open-source SDKs.", tags: ["Edge", "Infra", "Security"], repos: 610, stars: 54000, issues: 1700 },
  { login: "supabase", name: "Supabase", domain: "supabase.com", level: "beginner",
    tagline: "Open-source Firebase: Postgres, auth, storage, realtime — all MIT-ish.", tags: ["Backend", "Postgres", "BaaS"], repos: 240, stars: 108000, issues: 2100 },
  { login: "langchain-ai", name: "LangChain", domain: "langchain.com", level: "intermediate",
    tagline: "LangChain + LangGraph: the default plumbing for LLM apps and agents.", tags: ["Agents", "Chains", "Python"], repos: 120, stars: 138000, issues: 3300 },
  { login: "ollama", name: "Ollama", domain: "ollama.com", level: "beginner",
    tagline: "Run large models locally with one command; the off-ramp from cloud APIs.", tags: ["Local AI", "Go", "Models"], repos: 38, stars: 152000, issues: 1400 },
  { login: "n8n-io", name: "n8n", domain: "n8n.io", level: "beginner",
    tagline: "Fair-code workflow automation with 400+ integrations and AI nodes.", tags: ["Automation", "Workflows", "TS"], repos: 52, stars: 206500, issues: 2900 },
  { login: "langgenius", name: "Dify", domain: "dify.ai", level: "intermediate",
    tagline: "Production LLM app platform: agents, RAG pipelines, model ops in one UI.", tags: ["LLMOps", "RAG", "Platform"], repos: 30, stars: 157700, issues: 1100 },
  { login: "godotengine", name: "Godot Engine", domain: "godotengine.org", level: "advanced",
    tagline: "MIT-licensed game engine with a welcoming contributor community.", tags: ["Games", "C++", "Community"], repos: 90, stars: 96000, issues: 12800 },
  { login: "kubernetes", name: "Kubernetes", domain: "kubernetes.io", level: "advanced",
    tagline: "The CNCF flagship — SIG-structured, issue-labeled, huge mentorship paths.", tags: ["Infra", "Go", "CNCF"], repos: 140, stars: 124000, issues: 2400 },
  { login: "docker", name: "Docker", domain: "docker.com", level: "intermediate",
    tagline: "Compose, Buildx, and the tooling layer under half of CI.", tags: ["Containers", "Go", "DX"], repos: 190, stars: 82000, issues: 1500 },
  { login: "mozilla", name: "Mozilla", domain: "mozilla.org", level: "intermediate",
    tagline: "Firefox, Rust, Servo-adjacent research; deep docs for first contributions.", tags: ["Browsers", "Rust", "Privacy"], repos: 780, stars: 34000, issues: 4300 },
  { login: "wikimedia", name: "Wikimedia", domain: "wikimedia.org", level: "beginner",
    tagline: "Wikipedia's engineering org — very active Outreachy/GSoC mentoring.", tags: ["Open knowledge", "PHP", "Design"], repos: 1100, stars: 28000, issues: 3100 },
  { login: "gnome", name: "GNOME", domain: "gnome.org", level: "intermediate",
    tagline: "Linux desktop: apps, libs, and the Design skill tracks newcomers love.", tags: ["Desktop", "Vala", "Design"], repos: 950, stars: 26000, issues: 5800 },
  { login: "rust-lang", name: "Rust", domain: "rust-lang.org", level: "advanced",
    tagline: "Compiler, RFCs and cargo — herded by one of OSS's best team processes.", tags: ["Languages", "Systems", "RFCs"], repos: 110, stars: 102000, issues: 3700 },
  { login: "pytorch", name: "PyTorch", domain: "pytorch.org", level: "advanced",
    tagline: "The research default; strong-newcomer issues and a real review culture.", tags: ["AI/ML", "C++", "Research"], repos: 130, stars: 92000, issues: 6200 },
  { login: "tensorflow", name: "TensorFlow", domain: "tensorflow.org", level: "advanced",
    tagline: "Google's end-to-end ML stack; big surface area, mentored subprojects.", tags: ["AI/ML", "Infra", "Keras"], repos: 220, stars: 192000, issues: 4900 },
  { login: "flutter", name: "Flutter", domain: "flutter.dev", level: "beginner",
    tagline: "Google's UI SDK — triage is public and good-first-issues flow constantly.", tags: ["Mobile", "Dart", "UI"], repos: 170, stars: 174000, issues: 7600 },
  { login: "cncf", name: "CNCF", domain: "cncf.io", level: "intermediate",
    tagline: "Graduates projects like etcd and Prometheus; LFX mentored programs.", tags: ["Cloud native", "Programs", "DevRel"], repos: 120, stars: 15000, issues: 620 },
  { login: "jupyterlab", name: "Jupyter", domain: "jupyter.org", level: "beginner",
    tagline: "Notebooks everywhere: welcoming governance and beginner-labelled PRs.", tags: ["Data science", "Python", "Community"], repos: 95, stars: 46000, issues: 1900 },
  { login: "github", name: "GitHub", domain: "github.blog", level: "beginner",
    tagline: "Copilot, Actions, and the Hacktoberfest program the whole site orbits.", tags: ["Dev tools", "CI/CD", "AI"], repos: 850, stars: 78000, issues: 3800 },
];
