/* ══ About.tsx — mission, methodology, FAQ ══════════════════ */
import { Link } from "react-router-dom";
import { REPOS } from "../data/repos";
import { ORGS, PROGRAMS } from "../data/orgs";
import { HACKS } from "../data/hackathons";
import { CATEGORIES } from "../data/repos";
import { btn, Word } from "../components/ui";

const W = "max-w-[1240px] mx-auto px-6";

const FAQS: [string, string][] = [
  ["Where does the data come from?",
   "Every number on cyrus.ai starts from the public GitHub API. We snapshot the catalog once a fortnight - stars, forks, open issues, license, last push - and repo pages re-fetch contributors and language breakdowns live when you open them."],
  ["How do you decide what counts as a “skill” or an “MCP server”?",
   "A repo lands on a shelf if its own README says so: SKILL.md files for Agent Skills, .cursor/rules or mdc files for Cursor rules, AGENTS.md / DESIGN.md for configs, and an mcp server manifest or registry entry for MCP servers. Ambiguous repos go to the Dev Agents shelf."],
  ["Why rank by stars at all, if stars are hype?",
   "They're the only cross-repo signal that's public, historical and cheap to verify. We show forks, open issues and last-push beside every star count so a 200k repo that hasn't moved in a year doesn't pretend otherwise."],
  ["How do you keep hackathon dates honest?",
   `Every one of the ${HACKS.length} hackathons is checked against its official site or Devpost page before it ships. When an organizer hasn't published an exact date yet, the card carries a clearly-labelled estimate and we refresh it each fortnight.`],
  ["Can I list my own repository?",
   "Yes - save a bookmark on /projects for the submit flow we're shipping next: paste a GitHub URL, we enrich the metadata from the API, and your repo joins the review queue for the right shelf."],
  ["Is this affiliated with GitHub, Google or Anthropic?",
   "No. Logos belong to their owners, event names belong to their organizers, and this is an independent index. If anything here mislabels your project, tell us and we'll fix the snapshot."],
];

export default function About() {
  return (
    <>
      <header className={`${W} pt-14 pb-2`}>
        <p className="font-mono text-[10.5px] tracking-[.14em] uppercase text-dim">
          <Link to="/" className="hover:text-accent">Home</Link> / <span className="text-cocoa">About us</span>
        </p>
        <h1 className="font-display font-extrabold tracking-[-.02em] leading-[1.08] mt-3.5 mb-3 text-[clamp(33px,4.2vw,52px)]">
          An honest index for the <Word>agent era.</Word>
        </h1>
        <p className="text-ink font-medium max-w-[640px] text-[16.5px] leading-[1.6]">
          cyrus.ai exists because finding a good skill, rule pack, MCP server, hackathon or mentored program takes
          longer than shipping one. We cut that search to one keystroke.
        </p>
      </header>

      <div className={`${W} pt-8 pb-6 grid grid-cols-[1fr_320px] gap-10 items-start max-[980px]:grid-cols-1`}>
        <article className="max-w-[720px]">
          <h2 className="font-display font-extrabold text-[24px] tracking-[-.02em] mt-2 mb-3">What we track</h2>
          <p className="text-cocoa text-[15px] leading-[1.75] mb-4">
            {REPOS.length} repositories across {CATEGORIES.length} shelves - {CATEGORIES.map((c) => c.label).join(", ")} -
            published by {ORGS.length} curated organizations, plus the {PROGRAMS.length} mentored open-source programs
            those orgs join every year and the {HACKS.length} company hackathons with full prep plans. For each entry
            we keep the boring-but-decisive facts: stars, forks, open issues, language, license and last push.
          </p>
          <p className="text-cocoa text-[15px] leading-[1.75] mb-4">
            The directory is opinionated on purpose. A 67-skill pack by a solo builder sits next to Anthropic's
            official registry; an Outreachy internship is listed beside Google Summer of Code, and an NVIDIA
            hackathon beside both. If developers
            star it and it behaves like a skill, it's on a shelf.
          </p>

          <h2 id="data" className="font-display font-extrabold text-[24px] tracking-[-.02em] mt-9 mb-3 scroll-mt-24">Data &amp; methodology</h2>
          <p className="text-cocoa text-[15px] leading-[1.75] mb-4">
            Static stats come from a GitHub API snapshot dated <b className="text-ink">2026-10-02</b>, regenerated by a
            script that walks the seed list, refetches each repo and rewrites the dataset - nothing is typed by hand.
            Repo and organization pages then re-fetch contributors and language mixtures live, and fall back to
            clearly-labelled deterministic estimates when the API is rate-limited. Hackathon entries are rebuilt from
            official event pages and Devpost listings on the same cadence.
          </p>
          <ul className="text-cocoa text-[15px] leading-[1.75] grid gap-2 list-disc pl-6 mb-4">
            <li><b className="text-ink">Ranking</b> - stars first; forks and last-push always shown so ranking context survives.</li>
            <li><b className="text-ink">Difficulty labels</b> - derived, not claimed: beginner under 10k★, intermediate to 50k★, advanced above.</li>
            <li><b className="text-ink">Logos &amp; cover art</b> - official org avatars via GitHub; hackathon covers are generated SVG motifs in each event's signature color, never copied artwork.</li>
            <li><b className="text-ink">Sessions</b> - the demo sign-in and saved items live only in your browser's localStorage.</li>
          </ul>

          <h2 id="faq" className="font-display font-extrabold text-[24px] tracking-[-.02em] mt-9 mb-5 scroll-mt-24">Frequently asked</h2>
          <div className="faq">
            {FAQS.map(([q, a]) => (
              <details key={q} className="border border-line rounded-2xl bg-card mb-2.5 overflow-hidden shadow-soft">
                <summary className="list-none cursor-pointer px-5 py-[18px] font-semibold text-[15px] flex justify-between items-center gap-4 [&::-webkit-details-marker]:hidden">
                  {q}
                </summary>
                <div className="px-5 pt-0 pb-5 text-cocoa text-[14.5px] leading-[1.7]">{a}</div>
              </details>
            ))}
          </div>
        </article>

        <aside className="sticky top-[86px] max-[980px]:static grid gap-4">
          <div className="bg-card border border-line rounded-[20px] p-6 shadow-soft">
            <h3 className="font-display font-bold text-[16px] mb-4">Catalog at a glance</h3>
            {[
              [String(REPOS.length), "repos in the snapshot"],
              [String(ORGS.length), "organizations hand-picked"],
              [String(PROGRAMS.length), "mentorship programs tracked"],
              [String(HACKS.length), "hackathons with prep plans"],
              ["2026-10-02", "current snapshot date"],
            ].map(([v, l]) => (
              <div key={l} className="flex items-baseline justify-between gap-3 py-2.5 border-b border-liness last:border-0">
                <b className="font-mono text-[17px]">{v}</b><span className="text-cocoa text-[12.5px] text-right">{l}</span>
              </div>
            ))}
          </div>
          <div className="bg-peach border border-accent/20 rounded-[20px] p-6">
            <h3 className="font-display font-bold text-[16px] mb-2">Built by one developer, <Word>in Hyderabad.</Word></h3>
            <p className="text-rust text-[13px] leading-[1.65] mb-4">
              cyrus.ai is a solo project: a scraper, a design system and a grudge against “awesome lists”.
              Feedback, corrections and sponsorship suggestions all land in the same inbox.
            </p>
            <Link to="/organizations" className={btn("primary", "md", "w-full")}>Start with the orgs →</Link>
          </div>
        </aside>
      </div>
    </>
  );
}
