/* ══ fetch-orgs.mjs — real GitHub intel for the organizations directory ═
   Rebuilds src/data/realOrgs.ts from live GitHub data via the gh CLI
   (authenticated, no tokens in this repo):
     gh api users/{login}                      -> name, bio, blog, followers,
                                                 public_repos, avatar, joined
     gh api search/repositories?q=org:{login}  -> top 10 repos by stars
   Emits:
     REAL_ORGS   Org[] shaped entries for the /organizations directory
                 (honest numbers: stars/forks/issues summed over the top repos,
                 repos = public_repos, tagline = the org's own GitHub bio)
     REAL_REPOS  Record<login, RealRepo[]> - the org's flagship repos shown on
                 its profile page, exactly like the listing screenshots
     REAL_STATS  Record<login, { followers, joined, location }>
   Run: node scripts/fetch-orgs.mjs   (needs `gh auth status` to be logged in) ═ */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/data/realOrgs.ts");

/* the 26 directory logins + prominent additions so the page reads like the reference */
const LOGINS = [
  "google", "microsoft", "facebook", "anthropics", "openai", "huggingface", "pytorch", "tensorflow",
  "kubernetes", "cncf", "vercel", "cloudflare", "github", "langchain-ai", "ollama", "n8n-io",
  "supabase", "flutter", "rust-lang", "docker", "mozilla", "gnome", "godotengine", "wikimedia",
  "jupyterlab", "modelcontextprotocol", "langgenius",
  "nodejs", "golang", "django", "vuejs", "reactjs", "typescript", "sveltejs", "vitejs", "denoland",
  "grafana", "prometheus", "envoyproxy", "apache", "hashicorp", "gitlab", "posthog", "cypress-io",
];

const gh = (path) => JSON.parse(execFileSync("gh", ["api", path], { maxBuffer: 20 * 1024 * 1024, encoding: "utf8" }));
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const hostOf = (blog) => {
  if (!blog) return "";
  try { return new URL(blog.startsWith("http") ? blog : "https://" + blog).hostname.replace(/^www\./, ""); }
  catch { return blog.slice(0, 40); }
};
const clean = (s) => (s || "").replace(/\s+/g, " ").replace(/["\\]/g, "").trim();

const rows = [];
const reposMap = {};
const statsMap = {};
let fails = 0;

for (const login of LOGINS) {
  try {
    const u = gh(`users/${login}`);
    await sleep(120);
    let repos = [];
    try {
      const s = gh(`search/repositories?q=org:${login}&sort=stars&order=desc&per_page=10`);
      repos = s.items || [];
    } catch (e) { console.error(`  search fail ${login}: ${String(e.message).slice(0, 50)}`); }
    await sleep(2300); // search API: 30/min

    const stars = repos.reduce((a, r) => a + r.stargazers_count, 0);
    const issues = repos.reduce((a, r) => a + r.open_issues_count, 0);
    const langs = [...new Set(repos.map((r) => r.language).filter(Boolean))].slice(0, 3);
    const blog = hostOf(u.blog);
    rows.push({
      login,
      name: clean(u.name || login),
      domain: blog || `github.com/${login}`,
      level: stars > 300000 ? "advanced" : stars > 60000 ? "intermediate" : "beginner",
      tagline: clean(u.bio) || `Open-source organization on GitHub - ${u.public_repos} public repos.`,
      tags: langs.length ? langs : ["Open source"],
      repos: u.public_repos,
      stars,
      issues,
    });
    reposMap[login] = repos.map((r) => ({
      repo: r.full_name,
      desc: clean(r.description).slice(0, 150),
      lang: r.language || "Other",
      stars: r.stargazers_count,
      forks: r.forks_count,
      issues: r.open_issues_count,
      url: r.html_url,
    }));
    statsMap[login] = { followers: u.followers, joined: (u.created_at || "").slice(0, 7), location: clean(u.location) };
    console.log(`${login}: ${stars.toLocaleString()} top-repo stars, ${repos.length} repos`);
  } catch (e) {
    console.error(`FAIL ${login}: ${String(e.message).slice(0, 70)}`);
    fails++;
  }
}

if (!rows.length) { console.error("nothing fetched - realOrgs.ts left untouched"); process.exit(1); }

const esc = (s) => JSON.stringify(s);
const out = `/* ══ realOrgs.ts - LIVE GitHub intel for the organizations directory.
   Regenerated by: node scripts/fetch-orgs.mjs (gh api users/* + repo search,
   top 10 repos by stars per org). Every number here is GitHub's own: stars,
   forks, open issues, public repo counts, follower counts. ═ */
import type { Org } from "../lib/types";

export interface RealRepo { repo: string; desc: string; lang: string; stars: number; forks: number; issues: number; url: string }
export interface RealStat { followers: number; joined: string; location: string }

export const REAL_ORGS: Org[] = [
${rows.map((o) => `  { login: ${esc(o.login)}, name: ${esc(o.name)}, domain: ${esc(o.domain)}, level: ${esc(o.level)},\n    tagline: ${esc(o.tagline)}, tags: [${o.tags.map(esc).join(", ")}], repos: ${o.repos}, stars: ${o.stars}, issues: ${o.issues} },`).join("\n")}
];

export const REAL_REPOS: Record<string, RealRepo[]> = {
${rows.map((o) => `  "${o.login}": [\n${(reposMap[o.login] || []).map((r) => `    { repo: ${esc(r.repo)}, desc: ${esc(r.desc)}, lang: ${esc(r.lang)}, stars: ${r.stars}, forks: ${r.forks}, issues: ${r.issues}, url: ${esc(r.url)} },`).join("\n")}\n  ],`).join("\n")}
};

export const REAL_STATS: Record<string, RealStat> = {
${rows.map((o) => `  "${o.login}": { followers: ${statsMap[o.login].followers}, joined: ${esc(statsMap[o.login].joined)}, location: ${esc(statsMap[o.login].location)} },`).join("\n")}
};
`;
writeFileSync(OUT, out);
console.log(`wrote ${rows.length} orgs -> src/data/realOrgs.ts (${fails} failed)`);
